---
site_name: MyNotes
site_description: My notes about different technologies.
site_author: Adrián Martín García

repo_url: https://github.com/amartingarcia/notes

nav:
    - Home: index.md
## TO DO
#    - BBDD:
#        - Relational:
#        - NoSQL:
    - CI/CD:
#        - Azure Pipelines:
#        - Bitbucket:
#        - Github Actions:
#        - GitlabCI:
        - Jenkins:
            - cicd/jenkins/jenkins.md
            - Jenkinsfile: 
                - cicd/jenkins/jenkinsfile.md
                - Example 1: cicd/jenkins/jenkinsfiles/jenkinsfile_1.md
                - Example 2: cicd/jenkins/jenkinsfiles/jenkinsfile_2.md
                - Example 3: cicd/jenkins/jenkinsfiles/jenkinsfile_3.md
                - Example 4: cicd/jenkins/jenkinsfiles/jenkinsfile_4.md
                - Example 5: cicd/jenkins/jenkinsfiles/jenkinsfile_5.md
#    - Code:
#        - Go:
#        - Python:
#        - Shell Script:
#    - Configuration Management:
#        - Ansible:
#        - Ansible Tower:
#        - Ansible AWX:
#        - Chef:
#        - Puppet:
#        - Salt:
#        - Foreman:
#    - Containers:
#        - Docker:
#        - Dockerfiles:
#        - Registries:
    - Git:
        - Multi-accounts: git/multi_accounts.md
#    - Gitops:
#    - Infrastructure as Code:
#        - ARM:
#        - Cloudformation:
#        - Deployment Manager:
#        - Terraform:
#            - tflint:
#            - tfdocs:
#            - Terragrunt:
#    - Kafka:
    - Kubernetes:
        - Certifications:
            - CKA: kubernetes/certifications/cka.md
            - CKS: kubernetes/certifications/cks.md
        - Helm: 
            - kubernetes/helm/helm.md
            - helm-docs: kubernetes/helm/helm-docs.md
            - Helmfile: kubernetes/helm/helmfile.md
            - SOPS: kubernetes/helm/sops.md
        - Helmwave: kubernetes/helmwave.md
        - Kyverno: kubernetes/kyverno.md
        - kOps: kubernetes/kops.md
#    - Linux:
#    - Monitoring:
#        - Prometheus:
#            - Node Exporter:
#        - Loki:
#        - Promtail:
#        - Cloudwatch:
#    - Openshift:
#    - Public Cloud:
#        - Amazon Web Services:
#        - Google Cloud Platform:
#            - Training:
#                - GCP Cloud Engineer Associate: 
#        - Microsoft Azure:
#    - Private Cloud:
#        - Openstack:
    - QA:
        - Semantic Release: qa/semantic_release.md
        - Nexus: qa/nexus.md
        - Sonarqube: qa/sonarqube.md
    - Security:
        - Keycloak: 
            - security/keycloak.md
            - Jenkins: security/keycloak_jenkins.md
            - Nexus: security/keycloak_nexus.md
            - Sonarqube: security/keycloak_sonarqube.md

theme:
  name: readthedocs
  features:
    - navigation.tabs
  collapse_navigation: false
  hljs_languages:
    - yaml
    - dockerfile
    - groovy

markdown_extensions:
  # meta, toc, table and fenced_code extensions are included by default
  - extra
  - admonition
  - smarty
  - sane_lists
  - nl2br
  - toc:
      permalink: true

plugins:
  - search
...
