---
site_name: MyNotes
site_description: My notes about different technologies.
site_author: Adrián Martín García

repo_url: https://github.com/amartingarcia/notes

nav:
    - Home: index.md
    - BBDD:
        - Relational: bbdd/relational.md
        - NoSQL: bbdd/nosql.md
    - CI/CD:
        - Azure Devops: cicd/azuredevops.md
        - Bitbucket: cicd/bitbucket.md
        - Github Actions: cicd/github.md
        - GitlabCI: cicd/gitlabci.md
        - Jenkins: cicd/jenkins.md
    - Code:
        - Go: code/go.md
        - Python: code/python.md
        - Shell Script: code/shell.md
    - Configuration Management:
        - Ansible: configurationmanagement/ansible.md
    - Containers:
        - Docker: containers/docker.md
        - Dockerfiles: containers/dockerfiles.md
        - Registries: containers/registries.md
    - Git:
        - Multi-accounts: git/multi_accounts.md
    - Gitops:
        - ArgoCD: gitops/argocd.md
    - Infrastructure as Code:
        - Cloudformation: iac/cloudformation.md
        - Terraform: iac/terraform.md
    - Kubernetes:
        - CKA: kubernetes/certifications/cka.md
        - CKS: kubernetes/certifications/cks.md
        - Helm: kubernetes/helm/helm.md
        - Helmfile: kubernetes/helm/helmfile.md
        - Helmwave: kubernetes/helmwave.md
        - Kyverno: kubernetes/kyverno.md
        - kOps: kubernetes/kops.md
        - SOPS: kubernetes/helm/sops.md
    - Linux: linux/linux.md
    - Monitoring:
        - Prometheus: monitoring/prometheus.md
        - Loki: monitoring/loki.md
        - Promtail: monitoring/promtail.md
    - QA:
        - Semantic Release: qa/semantic_release.md
    - Queue: 
        - Kafka: queue/kafka.md
    - Security:
        - Keycloak: security/keycloak.md

theme:
  name: readthedocs
  features:
    - navigation.tabs
  collapse_navigation: false
  hljs_languages:
    - yaml
    - dockerfile
    - groovy

markdown_extensions:
  # meta, toc, table and fenced_code extensions are included by default
  - extra
  - admonition
  - smarty
  - sane_lists
  - nl2br
  - toc:
      permalink: true

plugins:
  - search
...
